//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphicTool
{
    using System;
    using System.Data.Entity;
    
    public partial class painDB_Entities : DbContext
    {
        public painDB_Entities()
            : base("name=painDB_Entities")
        {}
        public virtual DbSet<picture> pictures { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
